# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Logfile-EPrints
version:      1.01
version_from: lib/Logfile/EPrints.pm
installdirs:  site
requires:
    Date::Parse:                   0
    Geo::IP::PurePerl:             0
    LWP::UserAgent:                0
    Socket:                        0
    Text::CSV_XS:                  0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
